---

- name: install packages
  apt:
    update_cache: yes
    name:
      - nfs-client
      - rsync

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/miriel/S-Mandos
    state: directory
    mode: '0766'

- name: Copy config file for nfs
  copy:
     src: roles/backup/conf/fstab
     dest: /etc/fstab

- name: Mount an NFS volume
  ansible.posix.mount:
    src: 192.168.122.1:/sandbox/vagrant
    path: /home/miriel/S-Mandos
    opts: rw,relatime,vers=4.2,hard,proto=tcp,timeo=600,retrans=2,sec=sys,local_lock=none
    state: mounted
    fstype: nfs

- name: Create 'borg' user with a home directory
  ansible.builtin.user:
    name: borg
    uid: 1001
    create_home: yes

- name: Copy config file for ssh
  copy:
     src: roles/backup/conf/authorized_keys
     dest: /home/borg/.ssh/authorized_keys
     owner: borg
     group: borg

- name: Copy another config file for borg
  copy:
     src: roles/backup/conf/borgkey
     dest: /home/miriel/borgkey
     owner: borg
     group: borg

- name: Create crontab job for archiving "0 5 * * rsync -aAXzq /home/borg/*_repo /home/miriel/S-Mandos"
  ansible.builtin.cron:
    name: "copy backups to archive"
    minute: "0"
    hour: "5"
    job: "rsync -azq /home/borg/*_repo /home/miriel/S-Mandos"

- name: This command will copy repos from arcive
  ansible.builtin.shell:
    cmd: rsync -aAXz  /home/miriel/S-Mandos/*_repo /home/borg
  args:
    executable: /bin/bash
