---

- name: install haproxy
  apt:
    update_cache: yes
    name:
      - haproxy

- name: Copy config file for haproxy
  copy:
     src: roles/proxy2/conf/haproxy.cfg
     dest: /etc/haproxy/haproxy.cfg
 
- name: Just force systemd to reread configs
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: haproxy systemd service
  systemd_service:
     name: haproxy.service
     enabled: true
     state: restarted

