---

- name: restore postgresql master server and replace replica
  become: yes
  hosts: reserve
  roles:
    - name: postgres

- name: promote replica
  hosts: replica
  become: true
  tasks: 

    - name: Promote DB
      ansible.builtin.shell: |
        sudo -u postgres /usr/lib/postgresql/15/bin/pg_ctl promote -D /var/lib/postgresql/15/main/

    - name: postgresql systemd service restart
      systemd_service:
       name: postgresql.service
       state: restarted

- name: replace grafana config file and restart grafana
  hosts: grafana
  become: yes
  tasks: 
   - name: Copy config file for grafana
     copy:
       src: /home/miriel/Документы/Учеба/Otus/last/Ansible/roles/postgres/conf/grafana.ini
       dest: /etc/grafana/grafana.ini
   
   - name: Just force systemd to reread configs
     ansible.builtin.systemd_service:
       daemon_reload: true
  
   - name: grafana-server systemd service
     systemd_service:
         name: grafana-server.service
         enabled: true
         state: restarted

- name: replace grafana2 config file and restart grafana
  become: yes
  hosts: grafana2
  tasks: 
   - name: Copy config file for grafana
     copy:
       src: /home/miriel/Документы/Учеба/Otus/last/Ansible/roles/postgres/conf/grafana2.ini
       dest: /etc/grafana/grafana.ini
   
   - name: Just force systemd to reread configs
     ansible.builtin.systemd_service:
       daemon_reload: true
  
   - name: grafana2 systemd grafana-server.service
     systemd_service:
         name: grafana-server.service
         enabled: true
         state: restarted


